### PR TITLE
Changes for compatibility with v2 payment channels

### PR DESCRIPTION
**Pull request by mgoelzer**
- Changes every occurrence of `fil/1/paymentchannel` to `fil/2/paymentchannel`
 - Removes the `Proof` field of `UpdateChannelStateParameters` (per [this comment](https://github.com/filecoin-project/specs-actors/blob/4baf4d4b44d0ba6d9c78f95d5e20a4c95ee07fd1/actors/builtin/paych/paych_actor.go#L95) in Lotus source)

I've done some basic smoke tests on this and it seems to work.  Edit:  tested Create, Update (single voucher), Update (with multiple vouchers) and Settle.

### CODE REVIEW

**Comment by rllola** [comment]
It looks ok to me but it also mean we will not support v1 at all anymore. It could be problematic if other people use v1 currently... @jleni  Should will support both for now ?

**Comment by jleni** [comment]
Even if v1 is not available in the future, we would need an official confirmation that old v1 are not to be supported anymore.. Otherwise, we may introduce some problems.

**Comment by jleni** [comment]
In my opinion, if we extend support to v2, we need this to be part of the API and a new argument should be added.

**Comment by mgoelzer** [comment]
@rllola @jleni Thanks for taking some time to look at this.  I do have official confirmation that v1 payment channels are not supported anymore.  Chat with a Lotus core developer:

Screen Shot 2020-10-20 at 10 53 09 PM

The ultimate confirmation is that it's no longer possible to create a v1 payment channel anymore.  Here's an example on Lotus 0.10.2.  Trying mpoolPush'ing this message:

```
{
  Message: {
     To: 't01',
     From: 'f173kt4jpp344ly4ne6zc2wljmzdj7sdls6nrwuxi',
     Method: 2,
     Nonce: 9,
     Params: 'gtgqWBkAAVUAFGZpbC8xL3BheW1lbnRjaGFubmVsWC2CVQH+1T4l7984vHGk9kWrLSzI0/kNclUBSRPLlDrfP2tju2G2jdJJJsl4v+w=',
     Value: '3775',
     GasFeeCap: '16251176117',
     GasLimit: 10000000,
     GasPremium: '140625002',
  },
  Signature: 
   { Data: 'xTX58SoLEkD7C9lLW1Ei6uoCcL1YQRvWyZ+nvRFX1D00QR+aXu1uNS2AHUklCHfjnIrJw+Udwd8/6s9YTw15kQA=',
     Type: 1 
   }
}
```

(Note that the params string, when decoded to cbor, is using the old code cid `fil/1/paymentchannel`.  The cbor.me decoder will show that string.)  

The message will fail with ExitCode=18.  Now, go to the Lotus's log and you will see this message:  `caller type fil/2/account cannot exec actor type fil/1/paymentchannel (RetCode=18)`.

**Comment by jleni** [comment]
ok, that's good news. We would need to run rust fmt and fix the pending issues and let's merge this!

**Comment by jleni** [comment]
Merging to `externalPR` branch

**Pull request merged**
