### PR TITLE
removing harcoded code cid

### PR DESCRIPTION
**Pull request by rllola**
Need to update documentation. We now are using actor type and not code cid for deserialization.

:link: [zboto Link](https://app.clickup.com/t/32jyntc)

### CODE REVIEW

**Comment by rllola** [comment]
closes https://github.com/Zondax/filecoin-signing-tools/issues/673

**Comment by emmanuelm41** [comment]
@rllola we have issues again with arbitrary dep. I didn't have enough time to look into it. Could you do it please?

**Comment by rllola** [comment]
sure

**Comment by rllola** [comment]
@emmanuelm41 CI is now passing.

**Pull request merged**
