### PR TITLE
Migrate CircleCI to GitHub Actions

### LINKED ISSUE #390: Fix build issue in master + migrate to GitHub actions

### PR DESCRIPTION
**Pull request by emmanuelm41**
Closes #390

### CODE REVIEW

**Comment by emmanuelm41** [comment]
I. think we should squash everything and merge it.

**Review by jleni — CHANGES_REQUESTED** [review]
The badge in the readme.md for circleci should be removed and replaced with one for github actions.

**Comment by emmanuelm41** [comment]
> The badge in the readme.md for circleci should be removed and replaced with one for github actions.

Done!

**Comment by jleni** [comment]
> I. think we should squash everything and merge it.

Ok, I will squash too then

**Pull request merged**
